// ShiftWork.Mobile/app/(tabs)/upgrade.tsx
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Alert, Linking } from 'react-native';
import { useState } from 'react';
import { useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { registrationService } from '@/services/registration.service';
import { useAuthStore } from '@/store/authStore';
import { colors } from '@/styles/theme';

const FEATURES = [
  { label: 'Kiosk Clock-In / Out', free: true, pro: true },
  { label: 'Basic Scheduling', free: true, pro: true },
  { label: 'Sandbox Demo Data', free: true, pro: true },
  { label: 'Remove Sandbox Data', free: false, pro: true },
  { label: 'Advanced Scheduling', free: false, pro: true },
  { label: 'Analytics & Reports', free: false, pro: true },
  { label: 'Multi-Location Support', free: false, pro: true },
  { label: 'Data Export', free: false, pro: true },
];

export default function UpgradeScreen() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const companyId = useAuthStore((s) => s.companyId);

  const handleUpgrade = () => {
    if (!companyId) {
      Alert.alert('Error', 'No active company. Please sign in again.');
      return;
    }
    // For mobile MVP: deep-link to web upgrade page to stay out of PCI scope.
    // When a web URL is configured, open it. Otherwise simulate locally.
    const webUpgradeUrl = process.env.EXPO_PUBLIC_APP_URL
      ? `${process.env.EXPO_PUBLIC_APP_URL}/upgrade`
      : null;

    if (webUpgradeUrl) {
      Linking.openURL(webUpgradeUrl);
    } else {
      // Fallback: call API directly (stub payment method for dev)
      Alert.alert(
        'Upgrade to Pro',
        'This will upgrade your plan to Pro. Continue?',
        [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Upgrade',
            onPress: async () => {
              setLoading(true);
              try {
                const response = await registrationService.upgradePlan(companyId, {
                  stripePaymentMethodId: 'pm_stub_mobile',
                  targetPlan: 'Pro',
                });
                if (response.success) {
                  Alert.alert('Success!', `You are now on the ${response.plan} plan.`, [
                    { text: 'OK', onPress: () => router.back() }
                  ]);
                } else {
                  Alert.alert('Error', response.message);
                }
              } catch {
                Alert.alert('Error', 'Upgrade failed. Please try from the web app.');
              } finally {
                setLoading(false);
              }
            }
          }
        ]
      );
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <StatusBar style="dark" />
      <Text style={styles.title}>Upgrade to Pro</Text>
      <Text style={styles.subtitle}>Unlock the full power of ShiftWork for your team.</Text>

      {/* Feature comparison */}
      <View style={styles.tableCard}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={[styles.tableCell, styles.tableCellFeature]}>Feature</Text>
          <Text style={[styles.tableCell, styles.tableCellPlan]}>Free</Text>
          <Text style={[styles.tableCell, styles.tableCellPlan, styles.proPlanHeader]}>Pro ⭐</Text>
        </View>
        {FEATURES.map((f) => (
          <View key={f.label} style={styles.tableRow}>
            <Text style={[styles.tableCell, styles.tableCellFeature]}>{f.label}</Text>
            <Text style={[styles.tableCell, styles.tableCellPlan]}>{f.free ? '✅' : '❌'}</Text>
            <Text style={[styles.tableCell, styles.tableCellPlan]}>{f.pro ? '✅' : '❌'}</Text>
          </View>
        ))}
      </View>

      <TouchableOpacity style={styles.btnUpgrade} onPress={handleUpgrade} disabled={loading}>
        <Text style={styles.btnUpgradeText}>{loading ? 'Processing…' : 'Upgrade to Pro Now'}</Text>
      </TouchableOpacity>

      <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
        <Text style={styles.backBtnText}>← Back</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  content: { padding: 24, paddingBottom: 48 },
  title: { fontSize: 26, fontWeight: 'bold', color: colors.primary, marginBottom: 4 },
  subtitle: { color: colors.muted, marginBottom: 20 },
  tableCard: { backgroundColor: '#fff', borderRadius: 12, overflow: 'hidden', marginBottom: 24 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#f0f0f0', paddingVertical: 12 },
  tableHeader: { backgroundColor: '#f8f9fa' },
  tableCell: { paddingHorizontal: 12, fontSize: 14 },
  tableCellFeature: { flex: 2, color: '#333' },
  tableCellPlan: { flex: 1, textAlign: 'center' },
  proPlanHeader: { color: colors.primary, fontWeight: '700' },
  btnUpgrade: { backgroundColor: colors.primary, borderRadius: 10, padding: 16, alignItems: 'center', marginBottom: 12 },
  btnUpgradeText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  backBtn: { alignItems: 'center', padding: 12 },
  backBtnText: { color: colors.muted },
});

// ShiftWork.Angular/src/app/features/upgrade/upgrade.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { RegistrationService, PlanUpgradeRequest } from '../../core/services/registration.service';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-upgrade',
  templateUrl: './upgrade.component.html'
})
export class UpgradeComponent {
  isLoading = false;
  successMessage = '';
  errorMessage = '';

  // For MVP: no live Stripe integration on this page.
  // The user confirms intent; the backend handles Stripe via PlanService.
  // A real Stripe.js integration would capture card details here.
  mockPaymentMethodId = 'pm_stub_upgrade';

  constructor(
    private registrationService: RegistrationService,
    private authService: AuthService,
    private router: Router
  ) {}

  upgradeToPro(): void {
    this.isLoading = true;
    this.successMessage = '';
    this.errorMessage = '';

    // Get companyId from active session
    const companyId = this.authService.activeCompany?.companyId;
    if (!companyId) {
      this.errorMessage = 'No active company. Please sign in again.';
      this.isLoading = false;
      return;
    }

    const request: PlanUpgradeRequest = {
      stripePaymentMethodId: this.mockPaymentMethodId,
      targetPlan: 'Pro'
    };

    this.registrationService.upgradePlan(companyId, request).subscribe({
      next: (response) => {
        if (response.success) {
          this.successMessage = 'Upgrade successful! Your plan is now ' + response.plan + '.';
          // Redirect to dashboard after 2 seconds
          setTimeout(() => this.router.navigate(['/dashboard']), 2000);
        } else {
          this.errorMessage = response.message || 'Upgrade failed.';
        }
        this.isLoading = false;
      },
      error: () => {
        this.errorMessage = 'An error occurred during upgrade. Please try again.';
        this.isLoading = false;
      }
    });
  }
}

<div class="upgrade-container">
  <div class="upgrade-card">
    <h1>Upgrade to Pro</h1>
    <p class="subtitle">Unlock the full power of ShiftWork for your team.</p>

    <div *ngIf="successMessage" class="alert alert-success">{{ successMessage }}</div>
    <div *ngIf="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>

    <!-- Plan Comparison Table -->
    <div class="plan-comparison">
      <table class="comparison-table">
        <thead>
          <tr>
            <th>Feature</th>
            <th class="plan-col plan-free">Free</th>
            <th class="plan-col plan-pro">Pro ⭐</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Kiosk Clock-In / Out</td>
            <td>✅</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Basic Scheduling</td>
            <td>✅</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Sandbox Demo Data</td>
            <td>✅</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Remove Sandbox Data</td>
            <td>❌</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Advanced Scheduling</td>
            <td>❌</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Analytics & Reports</td>
            <td>❌</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Multi-Location Support</td>
            <td>❌</td>
            <td>✅</td>
          </tr>
          <tr>
            <td>Data Export</td>
            <td>❌</td>
            <td>✅</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="upgrade-cta">
      <p class="price-info">Pro plan — contact sales for pricing</p>
      <button
        class="btn btn-primary btn-lg"
        (click)="upgradeToPro()"
        [disabled]="isLoading">
        {{ isLoading ? 'Processing…' : 'Upgrade to Pro Now' }}
      </button>
      <p class="back-link"><a routerLink="/dashboard">← Back to Dashboard</a></p>
    </div>
  </div>
</div>
